# Build stage
FROM node:20-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .

ARG VITE_API_URL
ARG VITE_INTAKE_API_URL
ARG VITE_LIVEKIT_URL
ARG VITE_REPORT_API_URL
ARG VITE_REPORT_FALLBACK_DEMO
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY

ENV VITE_API_URL=$VITE_API_URL \
    VITE_INTAKE_API_URL=$VITE_INTAKE_API_URL \
    VITE_LIVEKIT_URL=$VITE_LIVEKIT_URL \
    VITE_REPORT_API_URL=$VITE_REPORT_API_URL \
    VITE_REPORT_FALLBACK_DEMO=$VITE_REPORT_FALLBACK_DEMO \
    VITE_SUPABASE_URL=$VITE_SUPABASE_URL \
    VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY

RUN npm run build

# Serve stage
FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/dist ./dist
RUN npm install -g serve
EXPOSE 8080
CMD ["serve", "dist", "-l", "8080", "--single", "--no-etag"]
